storage_account_name        = "saanvikitsa20230803"
public_ip_name              = "saanvikit-pubip"
network_security_group_name = "saanvikit-nsg"
network_interface_name      = "saanvikit-nic"
virtual_machine_name        = "saanvikit-vm"
virtual_machine_size        = "Standard_Ds1_v2"
adminUser                   = "saanvikit"